### ISSUE TITLE
Make wiki page for camp

### ISSUE THREAD

**Issue by bess** [curationexperts/Berlin2018#1]

**Comment by mark-dce** [comment]
Do you mean something like https://github.com/RepoCamp/ohsu2018/wiki ?

If that's what we need, I just need #3 completed and I can pretty quickly clone and update the version from OHSU (or we can wait and use the version from Duke).  We'll need to discuss a bit what parts to cut because of the reduced timeframe in Berlin (2 days of Samvera instead of 4)

**Comment by dwilcox** [comment]
I've created an event page on the DuraSpace wiki here: https://wiki.duraspace.org/display/FF/2018-11+Fedora+and+Samvera+Camp+Berlin
